### ISSUE TITLE
Issue with Browserify transform

### ISSUE THREAD

**Issue by anthonator** [esnext/esnext#70]
I'm having issues using esnext as a Browserify (v8.1.0) transform.

I'm getting the following error:

```
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at Visitor.PVp.visitWithoutReset (/Users/anthonator/Documents/Projects/clients/captivated-customer/prototype/node_modules/esnext/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:135:12)
    at Visitor.PVp.visit (/Users/anthonator/Documents/Projects/clients/captivated-customer/prototype/node_modules/esnext/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:117:21)
    at Function.transform (/Users/anthonator/Documents/Projects/clients/captivated-customer/prototype/node_modules/esnext/node_modules/regenerator/lib/visit.js:31:18)
    at transform (/Users/anthonator/Documents/Projects/clients/captivated-customer/prototype/node_modules/esnext/lib/index.js:87:23)
    at Function.compile (/Users/anthonator/Documents/Projects/clients/captivated-customer/prototype/node_modules/esnext/lib/index.js:34:9)
    at Stream.end (/Users/anthonator/Documents/Projects/clients/captivated-customer/prototype/node_modules/esnext/lib/index.js:160:31)
    at _end (/Users/anthonator/Documents/Projects/clients/captivated-customer/prototype/node_modules/esnext/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/anthonator/Documents/Projects/clients/captivated-customer/prototype/node_modules/esnext/node_modules/through/index.js:74:5)
    at Transform.onend (/Users/anthonator/Documents/Projects/clients/captivated-customer/prototype/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:180:16)
```

I've tried using the transform in my ```package.json``` and a gulp task. Both produce the same error.

```js
'use strict';

var browserify = require('browserify'),
    esnext     = require('esnext'),
    gulp       = require('gulp'),
    rename     = require('gulp-rename'),
    source     = require('vinyl-source-stream');

gulp.task('browserify', function() {
  return (
    browserify('./js/app.js', { debug: process.env.NODE_ENV !== 'production' })
      .transform(esnext)
      .bundle()
      .pipe(source('app.js'))
      .pipe(rename('bundle.js'))
      .pipe(gulp.dest('./js'))
  );
});
```

I figure I'm either doing something wrong or there might be a breaking change in Browserify 8.1.0.

**Comment by sent1nel** [comment]
+1

**Comment by fkling** [comment]
Probably the same issue as 6to5/6to5/issues/475

**Comment by eventualbuddha** [comment]
I'm having trouble reproducing this. @anthonator, what version of regenerator are you using? If you freeze it to 0.8.3 does it start working again?
